Разметка всех страниц
htmlacademy-htmlcss/1940523-sedona-34 pull request #2
Opened 2022-05-31 20:37 UTC by Tatii666

---
:mortar_board: [Разметка всех страниц](https://up.htmlacademy.ru/htmlcss/34/user/1940523/tasks/4)

:boom: https://htmlacademy-htmlcss.github.io/1940523-sedona-34/2/

2022-06-03 07:40 UTC, ant1quar requested changes

2022-06-03 07:40 UTC, ant1quar commented on hotels.html
> +        <button class="hotel-card-button button-favourite button">в избранное</button>
это ссылка

2022-06-03 07:40 UTC, ant1quar commented on hotels.html
> +    </ul>
тут можно сделать меньше вложений, просто расположив ссылки в div

2022-06-03 07:40 UTC, ant1quar commented on hotels.html
> +        <a class="button" href="https://vk.com/htmlacademy">
отсутствуют иконки социальных сетей

2022-06-03 07:40 UTC, ant1quar commented on index.html
> +              <h3 class="advantages-title">Там есть
Это можно сверстать одноуровневым списком. в дискорд-чате пример верстки

2022-06-03 07:40 UTC, ant1quar commented on index.html
> +              <a class="button" href="https://vk.com/htmlacademy">
отсутствуют иконки социальных сетей

2022-06-04 16:28 UTC, Tatii666 commented on hotels.html
> +        <button class="hotel-card-button button-favourite button">в избранное</button>
Исправила на ссылку

2022-06-04 16:29 UTC, Tatii666 commented on hotels.html
> +    </ul>
в nav. Исправлено

2022-06-04 16:29 UTC, Tatii666 commented on hotels.html
> +        <a class="button" href="https://vk.com/htmlacademy">
добавила иконки соц.сетей

2022-06-04 16:38 UTC, merged

2022-06-04 16:39 UTC, Tatii666 commented on index.html
> +              <h3 class="advantages-title">Там есть
Исправила

2022-06-04 16:39 UTC, Tatii666 commented on index.html
> +              <a class="button" href="https://vk.com/htmlacademy">
Добавила иконки